config/routes.rb
RecipeApp::Application.routes.draw do

  get "oauths/oauth"
  get "oauths/callback"

  get "logout" => "sessions#destroy", :as => "logout"
  resources :sessions, only: [:new, :create, :destroy]
  get "signin" => "sessions#new", :as => "signin"
#  match '/auth/:provider', to: 'sessions#new'
#  match '/auth/:provider/callback', to: 'sessions#create'
  resources :users 
  
  match "oauth/callback" => "oauths#callback"
  match "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  root to: 'recipes#index'

  resources :recipes do
    resources :directions, only: [:index, :create, :update, :destroy]
  end

  resources :favorites, only: [:create, :destroy]

end

app/models/direction.rb
class Direction < ActiveRecord::Base
  attr_accessible :text, :ingredient_entries, :title

  validates :title, presence: true
  validates :text, presence: true
  validates :ingredient_entries, presence: true

  belongs_to :recipe
  has_many :ingredient_entries

  #result
  has_one :result, dependent: :destroy

  def self.direction_ingredient_array(directions)
    result = []

    directions.each do |direction|
      result << Array(direction.ingredient_entries)
    end

    result
  end

  def results_array
    Array(ingredient_entries.reject{ |entry| entry.ingredient.nil? || entry.ingredient.type != 'Result' })
  end

  def ingredients_array
    Array(ingredient_entries.reject{ |entry| entry.ingredient.nil? || entry.ingredient.type == 'Result' })
  end

  def has_ingredient(ingredient)
    ingredients_array.include?(ingredient)
  end
end

app/controllers/directions_controller.rb
class DirectionsController < ApplicationController
  before_filter :fix_ingredient_entries, only: [:create]
  before_filter :setup_ingredient_entries

  def index
    @direction = @recipe.directions.new
  end

  def create
    @direction = @recipe.directions.create(params[:direction])

    if @direction.save
      flash[:success] = "Direction Added"
      @recipe.add_result_for @direction
    else
      flash[:alert] = "Error while adding direction"
      @invalid_direction = true;
    end

    render :index
  end

  def destroy
    direction = @recipe.directions.find(params[:id])
    direction.destroy
    flash[:success] = "Direction deleted!"
    redirect_to recipe_directions_path(@recipe)
  end

  private

    def fix_ingredient_entries
      if (params[:direction][:ingredient_entries].present?)
        params[:direction][:ingredient_entries] =
          params[:direction][:ingredient_entries].values.map! { |entry_id| IngredientEntry.find(entry_id) }
      end
    end

    def setup_ingredient_entries
      @recipe = Recipe.find(params[:recipe_id])
      @ingredient_entries = @recipe.ingredient_entries.reject { |entry| entry.direction.present? }
    end
end

app/views/directions/_directions_form.html.erb
<div>
  <%= form_for @direction, url: recipe_directions_path(@recipe,@direction) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <% hidden_field_tag :recipe, :id %>

    <section class="left-col">
      <%= label_tag "Used Ingredients" %> 

      <% if (@ingredient_entries.present?) then %>
        <% @ingredient_entries.each_with_index do |entry,index| %>
        <p>
          <div class="ingredient-list">
            <div class="ingredient-boxes pull-left">
              <%= check_box_tag 'direction[ingredient_entries[' + index.to_s + ']]', entry.id %>
            </div>
            <div class="ingredient-labels">
              <label> <%= entry %> </label>
            </div>
          </div>
        </p>
        <% end %>
      <% end %>
    </section>

    <section class="right-col">
      <%= f.label :title%>
      <%= f.text_field :title %>

      <%= f.label :text%>
      <%= f.text_area :text, rows: 10, cols: 11 %>
    </section>

    <section>
      <div class="add-button">
        <%= f.submit "Add Direction", class: "btn btn-large btn-primary" %>
      </div>
    </section>
  <% end %>
</div>

app/views/directions/_form.html.erb
<div>
  <%= form_for @direction, url: recipe_directions_path(@recipe,@direction) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <% hidden_field_tag :recipe, :id %>

    <section class="left-col">
      <%= label_tag "Used Ingredients" %> 

      <% if @ingredient_entries.present? %>
        <% @ingredient_entries.each_with_index do |entry,index| %>
        <p>
          <div class="ingredient-list">
            <div class="ingredient-boxes pull-left">
              <%= check_box_tag 'direction[ingredient_entries[' + index.to_s + ']]', entry.id %>
            </div>
            <div class="ingredient-labels">
              <label> <%= entry %> </label>
            </div>
          </div>
        </p>
        <% end %>
      <% end %>
    </section>

    <section class="right-col">
      <%= f.label :title%>
      <%= f.text_field :title %>

      <%= f.label :text%>
      <%= f.text_area :text, rows: 10, cols: 11 %>
    </section>

    <section>
      <div class="add-button">
        <%= f.submit "Add Direction", class: "btn btn-large btn-primary" %>
      </div>
    </section>
  <% end %>
</div>

app/views/directions/_layout.html.erb
<% @directions_layout = make_directions_layout(@recipe) %>

<div class="ingredients-col">
  <% @directions_layout[0].each do |entry| %>
    <li class="ingredients-row">
      <div class="ingredients-item">
        <%= entry %>
      </div>
    </li>
  <% end %>
</div>

<% @directions_layout.drop(1).each_with_index do |column,index| %>
  <div class="directions-col text-col<%= index %>" style="z-index:<%= 50 - 2 * index + 1 %>;position:relative;"></div>
  <div class="directions-col">
    <% column.each do |display_block| %>
      <% if (display_block.direction.nil?) %>
        <div class="directions-text" style="width:<%= display_block.display_width %>px;">
          <div class="empty-direction" style="width:<%= display_block.display_width %>px;">
          </div>
        </div>
      <% else %>
        <div class="directions-text" style="z-index:<%= 50 - 2 * index %>;">
          <div class="directions-present inactive-tab" style="width:<%= display_block.display_width %>px;" onclick="toggleActive(this); showText(<%= index %>,'<%= display_block.text %>', this);">
            <%= display_block.title %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/directions/_list.html.erb
<h3>Directions</h3>

<% @recipe.directions.each_with_index do |direction,index| %>
  <% if direction != @direction %>
    <div>
      <div class="clear-both">
        <h4>Step <%= (index + 1).to_s %>. <%= direction.title %></h4>
      </div>
      <div class="direction-ingredients pull-left">
        <% direction.ingredient_entries.each do |entry| %>
          <li><%= entry %></li>
        <% end %>
      </div>
      <div class="directions pull-left">
        <%= direction.text %>
      </div>
      <div class="clear-both">
        <%= link_to "delete", recipe_direction_path(@recipe,direction), method: :delete, data: { confirm: "You sure?" }, id:"delete-direction" %>
      </div>
    </div>
    <hr class="clear-both">
  <% end %>
<% end %>

app/views/directions/index.html.erb
<% provide(:title, "Edit Directions") %>
<h1>Edit Directions</h1>

<div id="form">
  <section id="directions_list">
    <%= render partial: "directions/list" %>
  </section>

  <section>
    <div id="directions_form">
      <% if (@invalid_direction) %>
        <%= render partial: "directions/form" %>
      <% else %>
        <div class="pull-left button-padding">
          <button class="btn btn-large btn-primary" id="add_directions_button" onclick="ShowDirectionsForm();"> Add New Direction </button>
        </div>

        <div class="pull-left button-padding">
          <%= link_to "Done", recipe_path(@recipe) ,class: "btn btn-large btn-primary", id: "Done" %>
        </div>

        <script>
          function ShowDirectionsForm() {
            $('#directions_form').html("<%= escape_javascript(render('directions/form')) %>");
          }
        </script>
      <% end %>
    </div>
  </section>
</div>