config/routes.rb
RecipeApp::Application.routes.draw do

  get "oauths/oauth"
  get "oauths/callback"

  get "logout" => "sessions#destroy", :as => "logout"
  resources :sessions, only: [:new, :create, :destroy]
  get "signin" => "sessions#new", :as => "signin"
#  match '/auth/:provider', to: 'sessions#new'
#  match '/auth/:provider/callback', to: 'sessions#create'
  resources :users 
  
  match "oauth/callback" => "oauths#callback"
  match "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  root to: 'recipes#index'

  resources :recipes do
    resources :directions, only: [:index, :create, :update, :destroy]
  end

  resources :favorites, only: [:create, :destroy]

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  attr_accessible :recipe, :user

  belongs_to :user
  belongs_to :recipe
end

app/controllers/favorites_controller.rb
class FavoritesController < AuthorizationController

  def create
    @user = User.find(params[:user_id])
    @recipe = Recipe.find(params[:recipe_id])

    @user.favorites.create!(recipe: @recipe)
    
    redirect_to :back
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    @recipe = @favorite.recipe
    @favorite.destroy
    redirect_to :back
  end
end

app/views/favorites/_form.html.erb
<% if logged_in? %>
  <% if @favorite.present? %>
    <span class="unfavorite">
      <%= button_to "", favorite_path(@favorite),  method: :delete %>
    </span>
  <% else %>
    <span class="favorite">
      <%= button_to "", controller: "favorites", action: "create", "user_id" => current_user.id, "recipe_id" => @recipe.id%>
    </span>
  <% end %>
<% end %>