config/routes.rb
RecipeApp::Application.routes.draw do

  get "oauths/oauth"
  get "oauths/callback"

  get "logout" => "sessions#destroy", :as => "logout"
  resources :sessions, only: [:new, :create, :destroy]
  get "signin" => "sessions#new", :as => "signin"
#  match '/auth/:provider', to: 'sessions#new'
#  match '/auth/:provider/callback', to: 'sessions#create'
  resources :users 
  
  match "oauth/callback" => "oauths#callback"
  match "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  root to: 'recipes#index'

  resources :recipes do
    resources :directions, only: [:index, :create, :update, :destroy]
  end

  resources :favorites, only: [:create, :destroy]

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  before_save :update_author

  attr_accessible :name, :description, :ingredient_entries, :ingredients, :user, :user_id, :author

  attr_accessible :picture
  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  belongs_to :user
  has_many :ingredient_entries, dependent: :destroy
  accepts_nested_attributes_for :ingredient_entries, :allow_destroy => true
  has_many :ingredients, through: :ingredient_entries
  accepts_nested_attributes_for :ingredients
  has_many :directions, dependent: :destroy
  accepts_nested_attributes_for :directions, :allow_destroy => true
  has_many :favorites

  validates :name, presence: true
  validates :description, presence: true
  validates :ingredient_entries, presence: true

  scoped_search on: [:name, :description, :author ]
  scoped_search in: :ingredients, on: :name

  def ingredients_text
    ingredient_entries.reject{ |entry| entry.ingredient.nil? ||entry.ingredient.type == 'Result' }.join("\n")
  end

  def results_array
    Array(ingredient_entries.reject{ |entry| entry.ingredient.nil? ||entry.ingredient.type != 'Result' })
  end

  def add_result_for(direction)
    ingredient_entries.create!(amount: "1 whole",
      ingredient: direction.result = Result.create!(name: "results from " + direction.title, direction: direction))
  end

  def get_result_from_ingredient_entries(direction)
    results_array.select{ |entry| entry.ingredient.direction == direction }.first
  end

  def has_picture?
    !picture.to_s.include?('missing.png')
  end

  def self.parse_and_create_ingredients(text)
    text.gsub(/(\A\s*$\n)|(\s*$)/,'').split(/$[^\z]/).map! do |entry|
      amount = entry.slice!(/^\d+ \w+ /)
      if (amount.present?) then amount.chop!() else return end

      #handles calls from parse_and_find_ingredients
      block_given? && yield(amount, entry) ||

      IngredientEntry.create!( amount: amount, ingredient: Ingredient.find_or_create_by_name(name: entry) )
    end
  end

  def self.parse_and_find_ingredients(text, recipe)
    parse_and_create_ingredients(text) do |amount, entry|
      Array(recipe.ingredient_entries.find_all_by_amount(amount)).find{|sub_entry|sub_entry.ingredient.name == entry}
    end
  end

  private
    def update_author
      self.author = user.try(:username) || "unknown user"
    end
end

app/controllers/recipes_controller.rb
class RecipesController < AuthorizationController
  skip_before_filter :require_login, only: [:index, :show]
  before_filter :parse_ingredients, only: [:create,:update]
  skip_load_and_authorize_resource only: [:create,:update]

  check_authorization

  def create
    @recipe = Recipe.new(params[:recipe])
    authorize! :create, @recipe

    if @recipe.save
      flash[:success] = "Recipe created!"
      redirect_to recipe_directions_path(@recipe)
    else
      flash.now[:alert] = "Error while creating recipe"
      render :new
    end
  end

  def new
    @recipe = Recipe.new
  end

  def index
    @recipes = Recipe.search_for(params[:search]).paginate(:page => params[:page] || 1, :per_page => 10)
  end

  def show
    @recipe = Recipe.find(params[:id])
    @favorite = @recipe.favorites.find_by_user_id(current_user)
  end

  def update
    @recipe  = Recipe.find(params[:id]) 
    authorize! :update, @recipe

    if @recipe.update_attributes(params[:recipe])
      flash[:success] = "Recipe updated!"
      redirect_to recipe_directions_path(@recipe)
    else
      flash.now[:alert] = "Error while updating recipe"
      render :edit
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def destroy
    Recipe.find(params[:id]).destroy
    flash[:success] = "Recipe deleted!"
    redirect_to recipes_path
  end

  private

    def parse_ingredients
      if (params.include?(:id))
        recipe = Recipe.find(params[:id])

        params[:recipe][:ingredient_entries] = Recipe.parse_and_find_ingredients(params[:recipe][:ingredients_text], recipe)

        recipe.results_array.each do |result|
          params[:recipe][:ingredient_entries] << result
        end

      else
        params[:recipe][:ingredient_entries] = Recipe.parse_and_create_ingredients(params[:recipe][:ingredients_text])
      end

      params[:recipe].delete(:ingredients_text)
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper

  def make_directions_layout(recipe)
    directions_layout = DisplayLayout.new([[],[]])

    recipe.directions.reverse_each do |direction|
      if (directions_layout.find_by_direction(direction).nil?)
        add_direction_to_layout(direction,directions_layout)
      end
    end

    return directions_layout
  end

  def add_direction_to_layout(direction, directions_layout)
    display_block = DisplayBlock.new(direction)

    direction.results_array.each do |entry|
      child = add_direction_to_layout entry.ingredient.direction, directions_layout

      display_block.add_child child
    end

    display_block.children.each do |child|
      directions_layout.add_spacing_for display_block, child
    end

    direction.ingredients_array.each do |entry|
      directions_layout.add_ingredient entry, display_block
    end
    
    directions_layout.add_block display_block

    return display_block
  end


  class DisplayBlock
    attr_accessor :title, :text, :direction, :width, :depth
    attr_accessor :child_index
    attr_accessor :children

    def initialize(args)
      if args.class == Direction
        @title = args.title
        @text = args.text
        @direction = args
        @width = args.ingredient_entries.length
        @depth = 1
      else
        @title = args[:title] || ""
        @text = args[:text] || ""
        @direction = args[:direction]
        @width = args[:width] || 1
        @depth = args[:depth] || 1
      end
      
      @children = []
    end

    def add_child(child)
      self.widen_by_size_of child
      self.deepen_more_than child
      @children << child
    end

    def deepen_more_than(child)
      if (self.depth <= child.depth)
        self.depth = child.depth + 1
      end
    end

    def widen_by_size_of(child)
      self.width += child.width - 1
    end

    def display_width
      width * 50
    end
  end


  class DisplayLayout < Array


    def find_by_direction(direction)
      self.flatten.select{ |n| n.class == DisplayBlock && n.direction.present? && n.direction == direction }.first
    end

    def add_ingredient(ingredient_entry, display_block)
      self[ 0 ] << ingredient_entry.to_s
      add_spacing_for display_block, nil
    end

    def add_spacing_for(display_block, child)
      if (child.nil?)
        (display_block.depth - 1).times do |index|
          self[index + 1] << DisplayBlock.new(depth: index + 1)
        end
      else
        placement_index = get_placement_index_for child

        (display_block.depth - child.depth - 1).times do |index|
          depth = index + child.depth + 1
          empty_block = DisplayBlock.new(depth: index + 1, width: child.width)
          real_index = get_real_index_from_depth_and_placement_index(depth,placement_index)

          self[depth].insert(real_index,empty_block)
        end
      end
    end

    def get_placement_index_for(display_block)
      cur_col = self[display_block.depth]
      @placement_index = 0;

      cur_col.each do |block|
        if (block != display_block)
          @placement_index += block.width
        else
          break
        end
      end

      return @placement_index
    end

    def get_real_index_from_depth_and_placement_index(depth, placement_index)
      cur_col = self[depth]
      
      block_index = 0;
      @real_index = 0;

      cur_col.each_with_index do |block, index|
        if (placement_index != block_index)
          block_index += block.width
          @real_index += 1
        else
          break
        end
      end

      return @real_index
    end

    def add_block(display_block)
      unless (self[display_block.depth])
        self << []
      end

      self[ display_block.depth ] << display_block
    end
  end
end

app/views/recipes/_byline.html.erb
<% if recipe.author.present? %>
   <% if recipe.user.present? %> 
    Submitted by <strong><%= link_to recipe.author, recipe.user %></strong>
  <% else %>
    Submitted by <%= recipe.author %>
  <% end %>
<% end %>

app/views/recipes/_create.js.erb
<% if (@state[:current_form] == "recipe_form") %>
  $("#form").html("<%= escape_javascript(render('recipes/recipe_form'))%>");
<% end %>

<% if (@state[:current_form] == "recipe_directions_form") %>
  $("#form").html("<%= escape_javascript(render('recipes/recipe_directions_form'))%>");

  $('#directions_list').html("<%= escape_javascript(render partial: 'directions/directions_list', formats: [:html])%>");

  <% if @state[:show_directions_form] %>
    $('#directions_form').html("<%= escape_javascript(render('directions/directions_form'))%>");
  <% else %>
    $('#directions_form').html("<%= escape_javascript(render('directions/directions_form_done'))%>");
  <% end %>
<% end %>

app/views/recipes/_directions_layout.html.erb
<% @directions_layout = make_directions_layout(@recipe) %>
<%= javascript_include_tag "rotate-cols" %>

<div class="ingredients-col">
  <% @directions_layout[0].each do |entry| %>
    <li class="ingredients-row">
      <div class="ingredients-item">
        <%= entry %>
      </div>
    </li>
  <% end %>
</div>

<% @directions_layout.drop(1).each_with_index do |column,index| %>
  <div class="directions-col text-col<%= index %>" style="z-index:<%= 50 - 2 * index + 1 %>;position:relative;">
  </div>
  <div class="directions-col">
    <% column.each do |display_block| %>
      <% if (display_block.direction.nil?) %>
        <div class="directions-text" style="width:<%= display_block.display_width %>px;">
          <div class="empty-direction" style="width:<%= display_block.display_width %>px;">
          </div>
        </div>
      <% else %>
        <div class="directions-text" style="z-index:<%= 50 - 2 * index %>;">
          <div class="directions-present" style="width:<%= display_block.display_width %>px;" onclick="toggleActive(this); showText(<%= index %>,'<%= display_block.text %>', this);">
            <%= display_block.title %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/recipes/_form.html.erb
<%= form_for @recipe, :html => { :multipart => true } do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <% if (current_user) %>
    <%= f.hidden_field :user_id, value: @recipe.user ? @recipe.user.id : current_user.id  %>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name, :placeholder => "Enter recipe name..." %>
  <div id="name_error">
    <br>
  </div>

  <section class="pull-right">
    <div class="picture-border">
      <% if @recipe.has_picture? %>
        <%= image_tag @recipe.picture.url(:thumb) %>
      <% end %>
    </div>
    <div>
      <%= f.file_field :picture %>
    </div>
  </section>

  <%= f.label :description %>
  <%= f.text_area :description, :placeholder => "Enter a brief description of the recipe...", class: "input_area" %>
  <div id="desc_error">
    <br>
  </div>

  <%= f.label :ingredients %>
  <%= f.text_area :ingredients_text, :placeholder => "Enter the ingredients for this recipe...", id: "Ingredients", class: "input_area" %>
  <div id="ingredient_error">
    <br>
  </div>


  <br>
  <br>
  <%= f.submit "Next", class: "btn btn-large btn-primary", id: "recipe_next" %>
<% end %>

app/views/recipes/_list.html.erb
<% recipes.each do |recipe| %>
  <div class="recipe-list-element" onclick="location.href='<%= root_url.chop + recipe_path(recipe) %>';">
    <section class="pull-right picture-border">
      <% if recipe.has_picture? %>
        <%= image_tag recipe.picture.url(:thumb) %>
      <% end %>
    </section>
    <section class="recipe-list-title">
      <%= link_to recipe.name, recipe %>
    </section>
    <section>
      <%= recipe.description %>
    </section>
    <div class="byline">
      <%= render partial: "recipes/byline", locals: { recipe: recipe } %> 
    </div>
    <section>
      <% favorites ||= false %>

      <% if favorites %>
        <% favorite = recipe.favorites.find_by_user_id(@user) %>
        <% if can? :destroy, favorite %>
          <%= link_to "unfavorite", favorite, method: :delete, data: { confirm: "You sure?" } %>
        <% end %>
      <% else %>
        <% if can? :destory, recipe %>
          <%= link_to "delete", recipe, method: :delete, data: { confirm: "You sure?" } %>
        <% end %>
      <% end %>
    </section>
  </div>

  <br>
<% end %>

<%= will_paginate recipes %>

app/views/recipes/_recipe_form.html.erb
<%= form_for @recipe do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, :placeholder => "Enter recipe name..." %>
  <div id="name_error">
    <br>
  </div>

  <%= f.label :description %>
  <%= f.text_area :description, :placeholder => "Enter a brief description of the recipe...", class: "input_area" %>
  <div id="desc_error">
    <br>
  </div>

  <%= f.label :ingredients %>
  <%= f.text_area :ingredients_text, :placeholder => "Enter the ingredients for this recipe...", id: "Ingredients", class: "input_area" %>
  <div id="ingredient_error">
    <br>
  </div>

<br>

  <%= f.submit "Next", class: "btn btn-large btn-primary", id: "recipe_next" %>
<% end %>

<%= javascript_include_tag "validate_input" %>

app/views/recipes/_recipe_list.html.erb
<% @recipes.each do |recipe| %>
  <div>
    <section>
      <%= link_to recipe.name, recipe %>
    </section>
    <section>
      <%= recipe.description %>
    </section>
    <section>
      <%= link_to "delete", recipe, method: :delete, data: { confirm: "You sure?" } %>
    </section>
  </div>
  <hr>
<% end %>

<%= will_paginate %>

app/views/recipes/edit.html.erb
<% provide(:title, "Edit Recipe") %>
<h1>Edit Recipe</h1>

<div id="form">
  <%= render :partial => "recipes/form" %>
</div>

app/views/recipes/index.html.erb
<% provide(:title, "Recipe Index") %>
<h1>Recipe Index</h1>

<div>
<%= form_tag recipes_path, method: 'get', remote: true do %>
  <p>
    <%= text_field_tag :search, params[:search], id: 'Search'  %>
    <%= submit_tag "Search", name: nil  %>
  </p>  
<% end %>
</div>

<div id="recipes_list"><%= render 'recipes/list', recipes: @recipes %><div>

app/views/recipes/index.js.erb
$("#recipes_list").html("<%= escape_javascript(render 'recipes/list', recipes: @recipes) %>");

app/views/recipes/new.html.erb
<% provide(:title, "New Recipe") %>
<h1>New Recipe</h1>

<div id="form">
  <%= render :partial => "recipes/form" %>
</div>

app/views/recipes/show.html.erb
<% provide(:title, @recipe.name) %>
<section class="clear-both">
  <div class="pull-left">
    <h1><%= @recipe.name %></h1>
  </div>

  <div class="pull-left">
    <span class="favorites">
      <br>
      <%= render "favorites/form" %>
    </span>
  </div>
</section>

<div class="byline clear-both">
  <%= render partial: "recipes/byline", locals: {recipe: @recipe } %> 
<div>

<br>

<section class="clear-both">
  <div class="left-col">
    <div class="picture-border">
      <% if @recipe.has_picture? %>
        <%= image_tag @recipe.picture.url(:medium) %>
      <% end %>
    </div>
  </div>

  <div class="right-col">
    <%= @recipe.description %>
  </div>
</section>

<br class="clear-both">

<br>

<section id="formatted-directions1">
  <%= render "directions/layout" %>
</section>
<br>

<section class="clear-both">    
  <% if can? :update, @recipe %>
    <span>
      <%= link_to "edit", edit_recipe_path(@recipe) %>
    </span>
  <% end %>
  <% if can? :destroy, @recipe %>
    <span>
      <%= link_to "delete", @recipe, method: :delete, data: { confirm: "You sure?" } %>
    </span>
  <% end %>
</section>