config/routes.rb
RecipeApp::Application.routes.draw do

  get "oauths/oauth"
  get "oauths/callback"

  get "logout" => "sessions#destroy", :as => "logout"
  resources :sessions, only: [:new, :create, :destroy]
  get "signin" => "sessions#new", :as => "signin"
#  match '/auth/:provider', to: 'sessions#new'
#  match '/auth/:provider/callback', to: 'sessions#create'
  resources :users 
  
  match "oauth/callback" => "oauths#callback"
  match "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  root to: 'recipes#index'

  resources :recipes do
    resources :directions, only: [:index, :create, :update, :destroy]
  end

  resources :favorites, only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="footer clear-both">
  <nav>
    <ul>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <h2 class="logo">
        <%= link_to "Recipe App", root_path %>
      </h2>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Recipes",  recipes_path %></li>
          <li><%= link_to "New Recipe",  new_recipe_path %></li>
          <% if !current_user %>
            <li><%= link_to "Sign Up",  new_user_path %></li>
            <li><%= link_to "Sign In",  new_session_path %></li>
          <% else %>
            <li><%= link_to current_user.username, user_path(current_user) %><li>
            <li><%= link_to "Sign Out", logout_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src = "http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key,value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>